workspace:
  base: /go
  path: src/bitbucket.org/joshdvir/vault-get

pipeline:
  build:
    image: golang:1.8
    pull: true
    environment:
      - VERSION=0.6.0
    commands:
      - apt-get update && apt-get install -y upx
      - mkdir /go/bin
      - mkdir -p prod
      - mkdir -p dist
      - curl https://glide.sh/get | sh
      - go get github.com/mitchellh/gox
      - go get github.com/tcnksm/ghr
      - glide install
      - glide update
      - gox -osarch-list
      - CGO_ENABLED=0 gox -ldflags "-s -w" -output "dist/vault-get-{{.OS}}-{{.Arch}}"
      - upx --help
      - upx -9 -t --best --brute dist/vault-get-linux-386
      - upx -9 -t --best --brute dist/vault-get-linux-amd64
      - upx -9 -t --best --brute dist/vault-get-linux-arm
      - upx -9 -t --best --brute dist/vault-get-windows-amd64.exe
      - upx -9 -t --best --brute dist/vault-get-windows-386.exe
      - upx -9 -t --best --brute dist/vault-get-darwin-amd64
      - upx -9 -t --best --brute dist/vault-get-darwin-386
      - ghr -t $GITHUB_TOKEN --replace -u devops-israel -r vault-get v$VERSION dist/
    secrets: [ github_token ]
